### PR TITLE
Update comment so generated files can be automatically recognized

### PR DESCRIPTION
**Pull request by ericwilson29**

### CODE REVIEW

**Comment by ericwilson29** [comment]
I signed it!

**Comment by pauleyj** [comment]
this looks good to me, any reason not to merge?

**Comment by suhaibmujahid** [comment]
Why this is not merged?

**Comment by scorsi** [comment]
@campoy can you please merge that PR ? Thanks !

**Comment by suhaibmujahid** [comment]
@campoy :)

**Review by campoy — APPROVED** [review]

**Pull request merged**
