### PR TITLE
Correct jsonenums go-generate example run

### PR DESCRIPTION
**Pull request by neurodrone**
Fixes a minor typo in the example.

### CODE REVIEW

**Comment by shurcooL** [comment]
There's another instance of word "stringer" being used instead of "jsonenums" on [line 8](https://github.com/campoy/jsonenums/blob/c80e0662c23bffdb3fe5e2162e893e44c35b21e3/jsonenums.go#L8). Maybe you could add a fix for that to your PR?

**Comment by neurodrone** [comment]
@shurcooL Good point. Addressed.

**Comment by shurcooL** [comment]
Thanks. :)

**Comment by shurcooL** [comment]
LGTM.

/cc @campoy You probably missed this PR.

**Comment by campoy** [comment]
Thanks!

**Pull request merged**
